import 'dart:io';
import 'package:csv/csv.dart';
import 'package:excel/excel.dart';
import 'package:flutter/foundation.dart';

class ParseResult {
  final List<Map<String, dynamic>> validRows;
  final int duplicatesRemoved;
  final List<String> errors;
  final int totalParsed;

  ParseResult({
    required this.validRows,
    required this.duplicatesRemoved,
    required this.errors,
    required this.totalParsed,
  });
}

class CsvExcelService {
  /// Parse CSV or Excel file bytes and return validated, deduplicated rows
  static Future<ParseResult> parseFile(Uint8List bytes, String fileName) async {
    final extension = fileName.split('.').last.toLowerCase();
    if (extension == 'csv') {
      return _parseCsv(bytes);
    } else if (extension == 'xlsx' || extension == 'xls') {
      return _parseExcel(bytes);
    }
    return ParseResult(
      validRows: [],
      duplicatesRemoved: 0,
      errors: ['Unsupported file format. Use CSV or Excel.'],
      totalParsed: 0,
    );
  }

  static Future<ParseResult> _parseCsv(Uint8List bytes) async {
    try {
      final content = String.fromCharCodes(bytes);
      final rows = const CsvToListConverter().convert(content, eol: '\n');
      if (rows.isEmpty) {
        return ParseResult(
            validRows: [], duplicatesRemoved: 0, errors: ['Empty file'], totalParsed: 0);
      }

      // First row = headers
      final headers = rows.first.map((e) => e.toString().toLowerCase().trim()).toList();
      final dataRows = rows.skip(1).toList();

      return _processRows(headers, dataRows);
    } catch (e) {
      debugPrint('CSV parse error: $e');
      return ParseResult(
          validRows: [], duplicatesRemoved: 0, errors: ['CSV parse error: $e'], totalParsed: 0);
    }
  }

  static Future<ParseResult> _parseExcel(Uint8List bytes) async {
    try {
      final excel = Excel.decodeBytes(bytes);
      final sheet = excel.tables[excel.tables.keys.first];
      if (sheet == null || sheet.rows.isEmpty) {
        return ParseResult(
            validRows: [], duplicatesRemoved: 0, errors: ['Empty sheet'], totalParsed: 0);
      }

      final headers = sheet.rows.first
          .map((cell) => cell?.value?.toString().toLowerCase().trim() ?? '')
          .toList();
      final dataRows = sheet.rows
          .skip(1)
          .map((row) => row.map((cell) => cell?.value ?? '').toList())
          .toList();

      return _processRows(headers, dataRows);
    } catch (e) {
      debugPrint('Excel parse error: $e');
      return ParseResult(
          validRows: [], duplicatesRemoved: 0, errors: ['Excel parse error: $e'], totalParsed: 0);
    }
  }

  static ParseResult _processRows(List<dynamic> headers, List<List<dynamic>> dataRows) {
    final List<Map<String, dynamic>> validRows = [];
    final List<String> errors = [];
    final Set<String> seenMobiles = {};
    int duplicatesRemoved = 0;

    // Map column names flexibly
    int nameIdx = _findCol(headers, ['name', 'customer name', 'नाव']);
    int mobileIdx = _findCol(headers, ['mobile', 'phone', 'mob', 'मोबाईल']);
    int villageIdx = _findCol(headers, ['village', 'गाव']);
    int talukaIdx = _findCol(headers, ['taluka', 'तालुका']);
    int addressIdx = _findCol(headers, ['address', 'पत्ता']);
    int solarIdx = _findCol(headers, ['solar_kw', 'solar kw', 'capacity', 'kw']);
    int consumerNoIdx = _findCol(headers, ['consumer_no', 'consumer no', 'consumer number']);

    // customer_id is AUTO-GENERATED by the database — ignore it from CSV
    final hasCustomerIdCol = _findCol(headers, ['customer_id', 'customer id', 'cust id']) != -1;
    if (hasCustomerIdCol) {
      errors.add('ℹ️ "Customer_Id" column detected — it will be IGNORED. '
          'Customer ID is auto-generated by the system (e.g. SIYA-0001). '
          'You do NOT need to add it to your CSV.');
    }

    if (nameIdx == -1 || mobileIdx == -1) {
      return ParseResult(
          validRows: [],
          duplicatesRemoved: 0,
          errors: ['Missing required columns: name and mobile'],
          totalParsed: 0);
    }

    for (int i = 0; i < dataRows.length; i++) {
      final row = dataRows[i];
      if (row.length <= mobileIdx) continue;

      final name = row[nameIdx].toString().trim();
      final mobile = _cleanMobile(row[mobileIdx].toString().trim());

      if (name.isEmpty) {
        errors.add('Row ${i + 2}: Missing name');
        continue;
      }
      if (mobile.length != 10 || !RegExp(r'^\d{10}$').hasMatch(mobile)) {
        errors.add('Row ${i + 2}: Invalid mobile "$mobile"');
        continue;
      }
      if (seenMobiles.contains(mobile)) {
        duplicatesRemoved++;
        continue;
      }

      seenMobiles.add(mobile);

      final map = <String, dynamic>{
        'name': name,
        'mobile': mobile,
        'status': 'P',
      };

      if (villageIdx != -1 && row.length > villageIdx) {
        map['village'] = row[villageIdx].toString().trim();
      }
      if (talukaIdx != -1 && row.length > talukaIdx) {
        map['taluka'] = row[talukaIdx].toString().trim();
      }
      if (addressIdx != -1 && row.length > addressIdx) {
        map['address'] = row[addressIdx].toString().trim();
      }
      if (solarIdx != -1 && row.length > solarIdx) {
        map['solar_kw'] = double.tryParse(row[solarIdx].toString().trim());
      }
      if (consumerNoIdx != -1 && row.length > consumerNoIdx) {
        map['consumer_no'] = row[consumerNoIdx].toString().trim();
      }
      // customer_id is intentionally NOT inserted — it's auto-generated by DB

      validRows.add(map);
    }

    return ParseResult(
      validRows: validRows,
      duplicatesRemoved: duplicatesRemoved,
      errors: errors,
      totalParsed: dataRows.length,
    );
  }

  static int _findCol(List<dynamic> headers, List<String> aliases) {
    for (final alias in aliases) {
      final idx = headers.indexWhere(
          (h) => h.toString().toLowerCase().contains(alias.toLowerCase()));
      if (idx != -1) return idx;
    }
    return -1;
  }

  static String _cleanMobile(String mobile) {
    // Remove +91, spaces, dashes
    return mobile.replaceAll(RegExp(r'[+\s\-()]'), '').replaceFirst('91', '', 0);
  }
}
